### ISSUE TITLE
Working with a newer version of Guzzle

### ISSUE THREAD

**Issue by Tschebel** [akeneo/php-crowdin-api#23]
Hi,

since Guzzle 3 has reached EOL, are there any plans to update your library to a newer version of guzzle?

edit: even better would be support of a psr-7 compatible abstraction layer like https://github.com/php-http/httplug

kind regards
Tschebel

**Comment by sagikazarmark** [comment]
Hey there,

Thanks for promoting HTTPlug.

If you are interested in it, I would be happy to provide a PR.

**Comment by nidup** [comment]
@Tschebel sorry for the very late answer and thank you for the hint, I discover HTTPlug :)
I'm pretty comfortable with guzzle that I already use on a bunch of projects / libs.
Guzzle 6.x seems also compatible with PSR7 (maybe not the case when you opened the issue).
Why should I use HTTPlug instead of Guzzle?

PS: to answer to the very first question, no problem to bump to a more recent version, we don't change often this library but it's still heavily used in our translation workflow. we'll just need to create a new dev branch to avoid to mess users.

**Comment by Tschebel** [comment]
hi,

since it was time critical and we only used 4 calls of the Crowdin API, we had to remove your library and implement them our self.

as for you questions:
yes guzzle 6 should work with psr7.
HTTPLug is an implementation on top of psr7 which provides an adapter like structure to connect to php clients other than guzzle.
PSR-7 only describes Request and Response not the client itself.
Thus you end up having a different syntax when creating and handling request and responses in two clients even if both implement psr-7. So basically if you use guzzle in your library, other people have to use guzzle too, even if they may have another client already installed. If your library uses HTTPlug you give people free choice which client they want to use as long as there is an adapter for httplug.
http://php-http.org/en/latest/clients.html 

kind regards
tschebel

**Comment by nidup** [comment]
Hi @Tschebel 

Thank you very much for the details!

It totally makes sense, for instance, in one of my projects, I use this crowdin lib + https://github.com/knplabs/php-github-api that both depends on Guzzle client implementation, so in my project i need to make sure that both versions of these lib use a Guzzle compatible version.

If both of those lib could depends only on PSR7 interfaces, I would be able to easily choose and use a single adapter (could be guzzle or something else) in my project.

**Comment by nidup** [comment]
After studying different possibilities, we'll bump to "guzzlehttp/guzzle": "~6.0"

**Comment by nidup** [comment]
This master is now using "guzzlehttp/guzzle": "~6.0", I will tag a new version today
